name: OS test

on:
  workflow_dispatch:

jobs:
  printos:
    name: Print OS name for each OS
    strategy:
      matrix:
        os:
          - ubuntu-20.04

    steps:
      - name: Print OS name
        shell: bash
        run: |
          echo "$RUNNER_OS"
          echo "$system"
